<Project>
  <PropertyGroup>
    <Version>0.4.7</Version>
    <AssemblyVersion>0.4.7.0</AssemblyVersion>
    <FileVersion>0.4.7.0</FileVersion>
    <InformationalVersion>0.4.7</InformationalVersion>
    <Company>jmvegas021</Company>
    <Product>GSPro Lighting</Product>
  </PropertyGroup>
</Project>
