<Project>
  <PropertyGroup>
    <Version>0.8.18</Version>
    <AssemblyVersion>0.8.18.0</AssemblyVersion>
    <FileVersion>0.8.18.0</FileVersion>
    <InformationalVersion>0.8.18</InformationalVersion>
    <Company>jmvegas021</Company>
    <Product>GSPro Lighting</Product>
  </PropertyGroup>
</Project>
